- name: webserver - install apache2 webserver with python3-mod_wsgi
  dnf:
    state: latest
    name:
      - httpd
      - httpd-devel
      - python3-mod_wsgi

- name: webserver - allow http via firewalld, enable immediately
  firewalld:
    zone: public
    service: http
    permanent: True
    state: enabled 
    immediate: True

- name: webserver - start apache2 webserver
  systemd:
    state: started
    name: httpd
